name: photo_view
description: photo_view fork
version: 0.1.0
homepage: https://github.com/robertodoering/photo_view

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.6.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0
  test: ^1.24.1

flutter:
